#!/usr/bin/env bash

# virtual_env_segment

# Set default symbols if not already defined in config
# Defaults should be standard symbols.
[[ -z ${PL_SYMBOLS[python]} ]] && PL_SYMBOLS[python]='π'

# -----------------------------------------------------------------------------
# append to prompt: python virtual environment name
# arg: $1 background color
# arg: $2 foreground color
function virtual_env_segment {
    if [ -n "$VIRTUAL_ENV" ]; then
        local venv="${VIRTUAL_ENV##*/}"
        local bg_color="$1"
        local fg_color="$2"
        local content=" ${PL_SYMBOLS[python]} $venv"
        PS1+="$(segment_content "$bg_color" "Default" " ")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content")"
        PS1+="$(segment_content "$bg_color" "Default" "")"
        __last_color="$bg_color"
    fi
}

